name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: config
      run: git config user.email "you@example.com"; git config user.name "test";
      
    - name: Run 
      run: make build
      env:
          SERVER_NAME: padserver.xyz
          APP_NAME: test
